name: Build XeLaTeX document

on:
  push:
  pull_request:

jobs:
  build_xelatex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile XeLaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: src
          latexmk_use_xelatex: true
          pre_compile: |
            apk add msttcorefonts-installer fontconfig
            update-ms-fonts
            fc-cache -f
      - uses: actions/upload-artifact@v2
        with:
          name: Document
          path: './**/*.pdf'
      - name: Deploy
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./src/main.pdf
